### ISSUE TITLE
Cannot process multiple emails at once. 

### ISSUE THREAD

**Issue by mehedi-sharif** [easydigitaldownloads/edd-product-updates#3]
While sending new campaigns it shows this error in a new window .
`Cannot process multiple emails at once. Please pause the email you are currently sending or wait for it to finish before attempting to send another. Close Window.
`
I badly want to use this plugin .

**Comment by cklosowski** [comment]
@mehedi-sharif This extension was removed from our offering more than a year ago.

This GitHub repository is here so past license holders can still gain access to the files if needed. At this point we are not releasing new updates to the extension however if you do have fixes you are more than welcome to use this repository to fork the product and maintain your own separate copy of it going forward.
